version: "3.2"
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
