service: ecs-nginx

configValidationMode: error

plugins:
  - serverless-dotenv-plugin
  - ./plugins/serverless-localstack

useDotenv: true

custom:
  awsAccountId: "000000000000"
  securityGroupIds: ${env:SECURITY_GROUPS}
  subnetIds: ${env:SUBNET_ID}
  s3:
    bucket: serverless-${self:service}-${opt:stage, self:provider.stage}
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    networks:
      - host
      - overlay
      - local_network
    docker:
      sudo: False
  tasks:
    config:
      clusterName: serverless-${self:service}-${opt:stage, self:provider.stage}

provider:
  name: aws
  profile: test
  region: us-east-1
  ecr:
    images:
      latest:
        path: ./
        file: docker/Dockerfile
        buildArgs:
          STAGE: ${opt:stage, self:provider.stage}
        cacheFrom:
          - serverless-${self:service}-${opt:stage, self:provider.stage}:latest
        platform: linux/amd64
  iam:
    role: EcsNginxRole
  vpc:
    securityGroupIds:
    - ${self:custom.securityGroupIds}
    subnetIds:
    - ${self:custom.subnetIds}
  stage: local

resources:
  # Log group
  - ${file(resources/log-group.yml)}
  # Role
  - ${file(resources/role.yml)}
  # # S3
  - ${file(resources/s3-bucket.yml)}
  # Cluster
  - ${file(resources/cluster.yml)}
  # Task
  - ${file(resources/task.yml)}
  # Service ECS
  - ${file(resources/service.yml)}
