service: ecs-nginx

configValidationMode: error

plugins:
  - serverless-dotenv-plugin
  - ./plugins/serverless-localstack
  - ./plugins/serverless-fargate

useDotenv: true

custom:
  awsAccountId: "000000000000"
  securityGroupIds: ${env:SECURITY_GROUPS}
  subnetIds: ${env:SUBNET_ID}
  s3:
    bucket: ${self:service}-${opt:stage, self:provider.stage}
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    networks:
      - host
      - overlay
      - local_network
    docker:
      sudo: False

provider:
  name: aws
  profile: test
  region: us-east-1
  ecr:
    images:
      latest:
        path: ./
        file: docker/Dockerfile
        buildArgs:
          STAGE: ${opt:stage, self:provider.stage}
        cacheFrom:
          - serverless-${self:service}-${opt:stage, self:provider.stage}:latest
        platform: linux/amd64
  iam:
    role: EcsNginxRole
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroupIds}
    subnetIds:
      - ${self:custom.subnetIds}
  stage: local

fargate:
  memory: "2GB"
  cpu: 1024
  logGroupName: ${self:service}-${opt:stage, self:provider.stage}-log-group
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroupIds}
    subnetIds:
      - ${self:custom.subnetIds}
    assignPublicIp: true
  tasks:
    BuildDocker:
      name: ${self:service}-${opt:stage, self:provider.stage}
      image: latest
      executionRoleArn: arn:aws:iam::${self:custom.awsAccountId}:role/${self:service}-${opt:stage, self:provider.stage}-execution-role
      taskRoleArn: arn:aws:iam::${self:custom.awsAccountId}:role/${self:service}-${opt:stage, self:provider.stage}-task-role

resources:
  # CloudWatch Logs
  - ${file(resources/cloudwatch-logs.yml)}
  # IAM Role
  - ${file(resources/iam-role.yml)}
  # # S3
  - ${file(resources/s3-bucket.yml)}
  # ECS Cluster
  - ${file(resources/ecs-cluster.yml)}
  # ECS Task
  - ${file(resources/ecs-task.yml)}
  # ECS Service ECS
  - ${file(resources/ecs-service.yml)}
