Resources:
  NginxService:
    Type: AWS::ECS::Service
    DependsOn:
      - EcsTargetGroup
        NginxTask
        FargateTasksCluster
        EcsNginxRole
        EcsNginxLoadBalancer
    Properties:
      ServiceName: ${self:service}-${opt:stage, self:provider.stage}-service
      Role: !Ref EcsNginxRole
      Cluster: !Ref FargateTasksCluster
      DesiredCount: 1
      TaskDefinition: !Ref NginxTask
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - ${self:custom.securityGroupIds}
          Subnets:
            - ${self:custom.subnetIds}
      LaunchType: FARGATE
      EnableExecuteCommand: true
      LoadBalancers:
        - ContainerName: ${self:service}
          LoadBalancerName: !GetAtt EcsNginxLoadBalancer.LoadBalancerName
          ContainerPort: 8000
          TargetGroupArn: !GetAtt EcsTargetGroup.TargetGroupArn
