Resources:
  EcsNginxRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${opt:stage, self:provider.stage}-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - ec2.amazonaws.com
                - glue.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${opt:stage, self:provider.stage}-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sqs:*"
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListObjects
                Resource:
                  - arn:aws:s3:::${self:custom.s3.bucket}*
  EcsNginxExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${opt:stage, self:provider.stage}-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
                - events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${opt:stage, self:provider.stage}-execution-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "ecs:RunTask"
                Resource: "*"
              - Effect: Allow
                Action: "iam:PassRole"
                Resource: "*"
                Condition:
                  StringLike:
                    "iam:PassedToService": "ecs-tasks.amazonaws.com"
              - Effect: Allow
                Action: "ecs:TagResource"
                Resource: "*"
                Condition:
                  StringEquals:
                    "ecs:CreateAction":
                      - RunTask
              - Effect: Allow
                Action: "iam:ListRoles"
                Resource: "*"
              - Effect: Allow
                Action: "iam:ListInstanceProfiles"
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  EcsNginxTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${opt:stage, self:provider.stage}-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: sts:AssumeRole