Resources:
  EcsNginxBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3.bucket}
      # Set the CORS policy
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            MaxAge: 3000

# Print out the name of the bucket that is created
Outputs:
  EcsNginxBucketName:
    Value:
      Ref: EcsNginxBucket